#!/bin/bash
# Test script untuk diagnosa form viewer routing issue

echo "===== Form Viewer Routing Diagnosis ====="
echo ""
echo "✅ Build status: $(npm run build > /dev/null 2>&1 && echo 'SUCCESS' || echo 'FAILED')"
echo ""
echo "📋 Checking Route Configuration:"
echo ""
echo "1. Route Definition in App.tsx:"
grep -A 5 "path=\"/f/:identifier\"" App.tsx || echo "❌ Route not found"
echo ""
echo "2. FormViewerWrapper Definition:"
grep -A 3 "const FormViewerWrapper" App.tsx || echo "❌ Wrapper not found"
echo ""
echo "3. RLS Policy for public forms access:"
grep -A 3 "Public can view forms" supabase_rls_policies.sql || echo "❌ RLS policy not found"
echo ""
echo "4. FormViewerPage Mounting:"
grep -A 2 "FormViewerPage.*Mounted" pages/FormViewerPage.tsx || echo "❌ Debug logging not found"
echo ""
echo "===== End Diagnosis ====="
